{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://synchronize",
			"OnPress": "/appconsumos_mb/Actions/app_consumos_prd/Service/SyncStartedMessage.action",
			"Title": "Sincronizar",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://headset",
			"OnPress": "/appconsumos_mb/Actions/Application/NavToSupport.action",
			"Title": "Ayuda",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/appconsumos_mb/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "Buscar Actualizaciones",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/appconsumos_mb/Actions/Application/NavToAbout.action",
			"Title": "Acerca de",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://reset",
			"OnPress": "/appconsumos_mb/Actions/Application/ResetMessage.action",
			"Title": "Salir App",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/appconsumos_mb/Actions/Application/Logout.action",
			"Title": "Cerrar Sesión",
			"Visible": "/appconsumos_mb/Rules/Application/ClientIsMultiUserMode.js"
		}
	]
}