{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Update_SolicitudesApp_Confirmar_Ingenio"
	},
	"OnSuccess": "/appconsumos_mb/Rules/Ingenio/Confirmar_Solicitud_Revision_Items_Ingenio.js",
	"Target": {
		"Service": "/appconsumos_mb/Services/app_consumos_prd.service",
		"EntitySet": "Solicitudes",
		"QueryOptions": "$filter=id eq {{#Page:Detalle_Solicitudes_Ingenio/#ClientData/id_de_solicitud}}"
	},
	"Properties": {
		"aprobador_ficha": "#Page:Main/#ClientData/info_user/ficha",
		"estado": "Aprobado",
		"fecha_revision": "/appconsumos_mb/Rules/get_Now_Datetime.js",
		"comentarios_aux": "#Page:Revision_Solicitud_Ingenio/#Control:FormCellNote_observaciones/#Value"
	}
}