{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Update_SolicitudesApp_Autorizar_Campo"
	},
	"OnFailure": {
		"Name": "/appconsumos_mb/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Error al actualizar la solicitud - {#ActionResults:Update_SolicitudesApp_Autorizar_Campo/error}",
			"Title": "Error"
		}
	},
	"OnSuccess": "/appconsumos_mb/Rules/Campo/PDF_Campo.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Actualizando Solicitud ...",
	"Target": {
		"Service": "/appconsumos_mb/Services/app_consumos_prd.service",
		"EntitySet": "Solicitudes",
		"QueryOptions": "$filter=id eq {{#Page:Autorizar_Solicitud_Campo/#ClientData/id_solicitud}}"
	},
	"Properties": {
		"autorizador_ficha": "#Page:Main/#ClientData/info_user/ficha",
		"estado": "Autorizado",
		"fecha_autorizado": "/appconsumos_mb/Rules/get_Now_Datetime.js"
	}
}