{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "Call_generatePDF"
	},
	"Target": {
		"Service": "/appconsumos_mb/Services/backend_REST.service",
		"Path": "/generatePDF",
		"RequestProperties": {
			"Method": "GET",
			"FetchCSRF": true
		}
	}
}