{
	"_Type": "Action.Type.BannerMessage",
	"OnSuccess": "/appconsumos_mb/Rules/get_Info_Usuario.js",
	"Message": "La sincronización de los datos falló - {#ActionResults:sync/error}",
	"Duration": 7,
	"Animated": true
}