{
	"_Type": "Action.Type.ProgressBanner",
	"OnFailure": "/appconsumos_mb/Actions/app_consumos_prd/Service/SyncFailureMessage.action",
	"OnSuccess": "/appconsumos_mb/Actions/app_consumos_prd/Service/UploadOffline.action",
	"Message": "Sincronización en proceso...",
	"CompletionMessage": "Sincronización completada",
	"CompletionTimeout": 7
}